import { Box, Button } from '@mui/material'
import dayjs from 'dayjs'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { DATE_FORMAT } from '../lib/frontend/constants'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box>Welcome</Box>
        <Button>
          <Link href={`/sessions/${dayjs().format(DATE_FORMAT)}/`}>
            <a>Today's Log</a>
          </Link>
        </Button>
      </main>
    </>
  )
}

export default Home
