name: CI
on: push
jobs:
  e2e:
    # this is the github environment that contains the "secrets" object
    environment: test
    # contains chrome, firefox, and edge browsers, and node
    # see: https://github.com/actions/runner-images?tab=readme-ov-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        # this is an undocumented alias to freeze the lockfile like npm ci
        # https://github.com/oven-sh/bun/pull/20590
        run: bun ci
      - name: Install playwright browsers
        run: bunx playwright install --with-deps
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      # note: build requires mongo to be running due to nextjs attempting SSG
      - name: Build app
        run: |
          cp .env.test .env.production
          bun run build
      - name: Run playwright tests
        env:
          # this is an arbitrary value for enabling dev user sign in
          # we are not importing secrets for external oauth providers
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          # renamed to AUTH_SECRET in authjs v5
          NEXTAUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: bunx playwright test

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun ci
      - name: Setup biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run biome
        run: bunx biome ci
      - name: Run vitest
        run: bun vi:once
      - name: 'Generate coverage report'
        # uncomment to generate reports if tests fail.
        # requires `reportOnFailure: true` in vite config.
        # if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          # set to "pr" to add a comment to the pr with the coverage stats
          # note: requires write permission to be enabled
          comment-on: 'none'
  scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install deps
        run: bun ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      - name: Run dev data generator
        run: bun db:dev
      - name: Run test data generator
        run: bun db:test
