name: CI
on: push
jobs:
  e2e:
    # this is the github environment that contains the "secrets" object
    environment: test
    # contains chrome, firefox, and edge browsers, and node
    # see: https://github.com/actions/runner-images?tab=readme-ov-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      # note: build currently requires mongo to be running to work
      - name: Build app
        run: |
          cp .env.test .env.production
          npm run build
      - name: Run playwright tests
        env:
          # this is an arbitrary value for enabling dev user sign in
          # we are not importing secrets for external oauth providers
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          # renamed to AUTH_SECRET in authjs v5
          NEXTAUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: npx playwright test

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run vitest
        run: npm run test:once
      - name: 'Generate coverage report'
        # uncomment to generate reports if tests fail.
        # requires `reportOnFailure: true` in vite config.
        # if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          # set to "pr" to add a comment to the pr with the coverage stats
          # note: requires write permission to be enabled
          comment-on: 'none'
  scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      - name: Run dev data generator
        run: npm run db:dev
      - name: Run test data generator
        run: npm run db:test
