name: CI
on: pull_request
jobs:
  e2e:
    # this is the github environment that contains the "secrets" object
    environment: test
    # contains chrome, firefox, and edge browsers, and node
    # see: https://github.com/actions/runner-images?tab=readme-ov-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start app
        env:
          # this is an arbitrary value for enabling dev user sign in
          # we are not importing secrets for external oauth providers
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          # renamed to AUTH_SECRET in authjs v5
          NEXTAUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        # we can't do npm build because nextjs overwrites NODE_ENV to be production
        # which disables the dev user login that cypress uses
        run: |-
          npm i 
          npm run dev:test &
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      - name: Cypress
        run: |-
          npm run cy:once -- --browser chrome --config defaultCommandTimeout=10000
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Vitest
        run: npm run test:once
  scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm i
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
      - name: Generate dev data
        run: npm run db:dev
      - name: Generate test data
        run: npm run db:test
